---
title: "**Are people willing to pay more for residential properties near transit stations?**"
author: "Ge (Chloe ) Qu"
date: "4/27/2018"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 Introduction
Transit-oriented Development (TOD) is a big concept in the field of urban planning and real estate development. TOD is a pattern of development which usually centers around a transit station, with high-density mixed-use properties located nearby and as it spreads out the density becomes lower. It is recognized as an effective way to to increase the ridership of public transit and reduce automobile dependency. It also maximizes the interactions between residentials, businesses, and leisure spaces, creating more walkable and livable urban spaces. 

Cities around the world have successfully followed this pattern to make themselves more compact and sustainable. In cities with dense population, such as Hong Kong and San Francisco, properties near major transit stations usually have the hottest market since the demand for these properties is much higher. As the fifth largest city in the US with limited land resources and existing city transit system, Philadelphia seems to be a suitable place for TOD. In fact, planning agencies of the City and the Region have been looking at opportunities for TOD in Philadelphia. A good question to ask first is that, does proximity to transit stations for a residential property have an influence on people's willingness to pay for it? 

To answer this question, in this project I will run statistical tests to see whether willingness to pay for residential properties near SEPTA transit stations is statistically significantly higher than that for other residentials. Market value per square footage is used as an indicator to measure willingness to pay. Since a quarter mile is usually a threshold for scale of walking, the influence of proximity to transit stations on the market values of residentials could be very different when the distances are within or beyond this threshold. Therefore, instead of using distance as an explanatory variable, I will use a dummy variable, $qrtmile$ to account for proximity, where $qrtmile=1$ means the nearest transit station for a residential property is within a quarter mile and $qrtmile=0$ means that is more than a quarter mile away. The hypotheses are as follows:

* $H_0$: Mean market values per square foot for residential properties within a quarter mile away from the nearest SEPTA station is equal to market values per square foot for properties located more than a quarter mile away from the nearest SEPTA station.

* $H_a$: Mean market values per square foot for residential properties within a quarter mile away from the nearest SEPTA station is greater than market values per square foot for properties located more than a quarter mile away from the nearest SEPTA station.

Apart from testing this hypothesis and exploring how distance to the nearest transit station would influence market value per square footage, additional variables will also be introduced to explain the variation in willingness to pay. These variables could represent the quality of a residential property itself, or the quality of the neighborhood a property resides in, which are both expected to have strong association with willingness to pay for this property.